### ISSUE TITLE
Module not available in Commerce after instalaltion 

### ISSUE THREAD

**Issue by Spheerys** [poconosewandvac/Commerce_StorePickup#1]
Hi :)

I'm trying to install your extra on Commerce 1.2.1-pl and after installation from modx.com store, I don't see it inside Commerce's modules.

Do you have any idea from where the issue is coming from ?

**Comment by tonyklapatch** [comment]
Thanks for report, sorry for the delay in fixing this. New release 1.0.1 fixes this issue.

**Comment by Spheerys** [comment]
Thanks !
